version: "3.9"
services:
  webapp:
    image: public.ecr.aws/k6j1l5m9/pmj-node-app:latest
    restart: always
    container_name: web-app-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: public.ecr.aws/lts/mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    container_name: mysql-container
    ports:
      - "3306:3306"