version: "3.9"
services:
  webapp:
    image: node-app:latest
    restart: always
    container_name: web-app-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
      - TZ=Asia/Seoul
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    container_name: mysql-container
    ports:
      - "3306:3306"





